version: 2.1
      
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  
parameters:
  github_actions_event:
    type: string
    default: ""
  preview_folder_name:
    type: string
    default: ""
    
jobs:
  build-app:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Build app
          command: |
            mkdir build
            cp -a ./src/. ./build
      - persist_to_workspace:
          root: .
          paths:
            - build
  release:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Release build
          command: |
            # Upload to S3 in a folder named with the current branch
            if [[ $CIRCLE_BRANCH == "main" ]]; then
              aws s3 rm s3://web-build-preview-workflow --recursive --exclude "preview/*"
              aws s3 sync ./build s3://web-build-preview-workflow
            else
              aws s3 sync ./build s3://web-build-preview-workflow/preview/$CIRCLE_BRANCH --delete
            fi
            
            # Invalidate CloudFront
            aws cloudfront create-invalidation --distribution-id E1V5I0HOA197UY --paths "/*"
  delete-preview-folder:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Delete Web preview folder
          command: |
            # Check if folder exists
            # index.html will always be present, so we can check for its existence
            aws s3api head-object --bucket web-build-preview-workflow --key preview/<< pipeline.parameters.preview_folder_name >>/index.html || not_exist=true
            
            if [[ $not_exist ]]; then
              echo "Preview folder does not exist."
            else
              aws s3 rm s3://web-build-preview-workflow/preview/<< pipeline.parameters.preview_folder_name >> --recursive
              
              # Invalidate CloudFront
              aws cloudfront create-invalidation --distribution-id E1V5I0HOA197UY --paths "/preview/<< pipeline.parameters.preview_folder_name >>/*"
              
              echo "Preview folder has been deleted."
            fi
    
          
workflows:
  build-and-deploy:
    when:
      not: << pipeline.parameters.github_actions_event >>
    jobs:
      - approve-build:
          type: approval
      - build-app:
          requires:
            - approve-build
      - release:
          requires:
            - build-app
  delete-preview:
    when:
      and:
        - equal: [ delete, << pipeline.parameters.github_actions_event >> ] 
        - not: 
            matches:
              pattern: "^main$"
              value: << pipeline.parameters.preview_folder_name >>
    jobs:
      - delete-preview-folder
