version: 2.1
      
orbs:
  aws-cli: circleci/aws-cli@3.1.4
      
jobs:
  build-app:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: Build app
          command: |
            mkdir build
            cp -a ./src/. ./build
      - persist_to_workspace:
          root: .
          paths:
            - build
  release:
    executor: aws-cli/default
    parameters:
      branch_name:
        type: string
        default: main
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Release build
          command: |
            # Upload to S3 in a folder named with the current branch
            if [[ << parameters.branch_name >> == "main" ]]; then
              aws s3 rm s3://web-build-preview-workflow --recursive --exclude "preview/*"
              aws s3 sync ./build s3://web-build-preview-workflow
            else
              aws s3 sync ./build s3://web-build-preview-workflow/preview/$CIRCLE_BRANCH --delete
            fi
            
            # Invalidate CloudFront
            aws cloudfront create-invalidation --distribution-id E1V5I0HOA197UY --paths "/*"
          
workflows:
  build-and-deploy:
    jobs:
      - approve-build:
          type: approval
      - build-app:
          requires:
            - approve-build
      - release:
          branch_name: $CIRCLE_BRANCH
          requires:
            - build-app
