name: Branch deletion

on:
  delete
    
jobs:
  trigger-circleci-delete-preview-workflow:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI API
        run: |
          curl -X POST --location "https://circleci.com/api/v2/project/github/vjcagay/web-build-preview-workflow/pipeline" \
            -H "Content-Type: application/json" \
            -H "Circle-Token: ${{ secrets.CCI_TOKEN }}" \
            -d "{ \"branch\" : \"main\", \"parameters\": { \"github_actions_event\": \"delete\", \"preview_folder_name\": \"${{ github.event.ref }}\" } }"
          
